name: _merge_master

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

jobs:
  merge_master:
    runs-on: ubuntu-latest
    steps:
      # verify version format
      - name: Verify version format
        shell: bash
        run: |
          if ! [[ "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format."
            exit 1
          fi
      
      # checkout dev
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      
      # update package version
      - name: Update package.json version
        shell: bash
        run: |
          NEW_VERSION="${{ github.event.inputs.version }}"
          sed -i 's/"version": ".*"/"version": "'"$NEW_VERSION"'"/' package.json
      
      # commit changes
      - name: Commit changes
        shell: bash
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "support@alphainsider.freshdesk.com"
          git add package.json
          if git diff --staged --quiet; then
            echo "Skipping, no changes to commit."
          else
            git commit -m "Updated version"
            git push origin dev
          fi
      
      # merge dev to master
      - name: Merge dev to master
        shell: bash
        run: |
          git fetch origin master
          git checkout master
          if git diff origin/master..origin/dev --quiet; then
            echo "Skipping, no changes between dev and master."
          else
            git merge origin/dev --no-ff -m "Merged dev to master"
            git push origin master
          fi