name: _update_version

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      # verify version format
      - name: Verify version format
        shell: bash
        run: |
          if ! [[ "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format."
            exit 1
          fi
      
      # checkout master
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      
      # update package version
      - name: Update package version
        shell: bash
        run: |
          NEW_VERSION="${{ github.event.inputs.version }}"
          sed -i 's/"version": ".*"/"version": "'"$NEW_VERSION"'"/' package.json
      
      # push changes master
      - name: Push changes master
        shell: bash
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "support@alphainsider.freshdesk.com"
          git add package.json
          if git diff --staged --quiet; then
            echo "Skipping, no changes to commit."
          else
            git commit -m "Updated version"
            git push origin master
          fi