name: NEW_RELEASE

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version Number (eg: 0.0.0)'

permissions:
  contents: write

jobs:
  # merge master
  merge_master:
    uses: ./.github/workflows/_merge_master.yml
    with:
      version: ${{ github.event.inputs.version }}
  
  # new release
  new_release:
    needs: merge_master
    runs-on: ubuntu-latest
    steps:
      # create release
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: master
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
          draft: true